apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot-www-pvc
  namespace: go-blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot-conf-pvc
  namespace: go-blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
