apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: go-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-backend-image:latest
          env:
            - name: GIN_MODE
              value: release
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: gouser
            - name: DB_PASSWORD
              value: gopassword
            - name: DB_NAME
              value: goblog
          ports:
            - containerPort: 8080
