services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: go-blog-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - go-modules:/go/pkg/mod
    environment:
      - GIN_MODE=debug
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: go-blog-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - ASTRO_PORT=3000
      - HOST=0.0.0.0 # 모든 네트워크 인터페이스에 바인딩
    depends_on:
      - backend

  mysql:
    platform: linux/amd64
    build: ./mysql
    container_name: go-blog-mysql-dev
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql-data-dev:
    driver: local
  go-modules:
    driver: local

networks:
  go-blog-network-dev:
    driver: bridge
