services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: go-blog-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - go-modules:/go/pkg/mod
    environment:
      - GIN_MODE=debug
    depends_on:
      - mysql
    env_file: .env.dev
    networks:
      - go-blog-network-dev

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: go-blog-frontend-dev
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - ASTRO_PORT=4321
      - HOST=0.0.0.0
    command: ["bun", "run", "dev", "--host"]
    depends_on:
      - backend
    env_file: .env.dev
    networks:
      - go-blog-network-dev

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile.dev
    container_name: go-blog-mysql-dev
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file: .env.dev
    networks:
      - go-blog-network-dev

volumes:
  mysql-data-dev:
    driver: local
  go-modules:
    driver: local
  node_modules:
    driver: local

networks:
  go-blog-network-dev:
    driver: bridge
