version: "3.8"

services:
  backend:
    build: ./backend
    container_name: go-blog-backend
    expose:
      - "8080"
    environment:
      - GIN_MODE=release
    env_file: .env # .env 파일에서 환경 변수 로드
    depends_on:
      - mysql
    networks:
      - go-blog-network

  frontend:
    build: ./frontend
    container_name: go-blog-frontend
    expose:
      - "3000"
    env_file: .env # .env 파일에서 환경 변수 로드
    depends_on:
      - backend
    networks:
      - go-blog-network

  mysql:
    build: ./mysql
    container_name: go-blog-mysql
    expose:
      - "3306"
    env_file: .env # .env 파일에서 환경 변수 로드
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - go-blog-network

  nginx:
    build: ./nginx
    container_name: go-blog-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt-data:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    env_file: .env # .env 파일에서 환경 변수 로드
    depends_on:
      - backend
      - frontend
    networks:
      - go-blog-network
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local
  letsencrypt-data:
    driver: local
  certbot-webroot:
    driver: local

networks:
  go-blog-network:
    driver: bridge
