version: "3.8"

services:
  nginx-initial:
    image: nginx:latest
    container_name: go-blog-nginx-initial
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx.initial.conf:/etc/nginx/conf.d/nginx.conf.template
      - ./certbot/www:/var/www/certbot
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    entrypoint: >
      /bin/sh -c "envsubst '$$DOMAIN $$EMAIL' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - go-blog-network
    restart: unless-stopped

  certbot-initial:
    image: certbot/certbot:latest
    container_name: go-blog-certbot-initial
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file:
      - .env
    command: certonly --webroot --webroot-path /var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN} --force-renewal
    networks:
      - go-blog-network
    depends_on:
      - nginx-initial
    restart: unless-stopped

networks:
  go-blog-network:
    driver: bridge
