version: "3.8"

services:
  backend:
    build: ./backend
    container_name: go-blog-backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    depends_on:
      - mysql
    networks:
      - go-blog-network

  frontend:
    build: ./frontend
    container_name: go-blog-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - go-blog-network

  mysql:
    build: ./mysql
    container_name: go-blog-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - go-blog-network

  nginx:
    build: ./nginx
    container_name: go-blog-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - go-blog-network

volumes:
  mysql-data:
    driver: local

networks:
  go-blog-network:
    driver: bridge
