version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: go-blog-nginx-initial
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx.initial.conf:/etc/nginx/conf.d/nginx.conf
      - ./certbot/www:/var/www/certbot
    networks:
      - go-blog-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: go-blog-certbot-initial
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file:
      - .env
    command: certonly --webroot --webroot-path /var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
    networks:
      - go-blog-network
    depends_on:
      - nginx
    restart: unless-stopped

networks:
  go-blog-network:
    driver: bridge
