services:
  app:
    build:
      target: backend-builder
    volumes:
      - ./backend:/app
    command: air -c .air.toml
    environment:
      - GIN_MODE=debug

  frontend:
    image: oven/bun:1.2.5
    working_dir: /app/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - frontend_bun_cache:/root/.bun
    command: sh -c "bun install && bun run dev"

volumes:
  frontend_bun_cache:
