version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=gouser
      - DB_PASSWORD=gopassword
      - DB_NAME=goblog
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: goblog
      MYSQL_USER: gouser
      MYSQL_PASSWORD: gopassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
