entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
certificatesResolvers:
  myresolver:
    acme:
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      email: "${EMAIL}"
      storage: "/letsencrypt/acme.json"
      keyType: "EC256"
      httpChallenge:
        entryPoint: web
