apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: go-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: your-nginx-image:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: certbot-www
              mountPath: /var/www/certbot
            - name: certbot-conf
              mountPath: /etc/letsencrypt
      volumes:
        - name: certbot-www
          persistentVolumeClaim:
            claimName: certbot-www-pvc
        - name: certbot-conf
          persistentVolumeClaim:
            claimName: certbot-conf-pvc
