apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: go-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-frontend-image:latest
          env:
            - name: NODE_ENV
              value: production
            - name: VITE_API_URL
              value: /api
          ports:
            - containerPort: 3000
